id: I8174CCF9
legacy_id: P000764
ocr_import_info:
  bdrc_scan_id: W1KG12299
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T14:52:24'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T03:27:02.564663+00:00'
last_modified: 2022-08-31 11:27:15.845673
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG12299
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG12299
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བོ་དོང་ཕྱོགས་ལས་རྣམ་རྒྱལ་གྱིས་མཛད་པའི་དཔལ་དེ་ཁོ་ན་ཉིད་འདུས་པའི་སྙིང་པོ།
  author: བོ་དོང་པཎ་ཆེན་ཕྱོགས་ལས་རྣམ་རྒྱལ།
statistics:
  ocr_word_mean_confidence_index: 0.554172907108775
  ocr_word_median_confidence_index: 0.5600000023841858
quality: null
bases:
  I1KG12312:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12312
      total_pages: 342
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG12312.txt
    statistics:
      ocr_word_median_confidence_index: 0.5600000023841858
      ocr_word_mean_confidence_index: 0.554172907108775
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
