id: I8174CCF9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T14:54:44+00:00'
last_modified: '2022-06-07T13:39:49.533202+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12299
  title: བོ་དོང་ཕྱོགས་ལས་རྣམ་རྒྱལ་གྱིས་མཛད་པའི་དཔལ་དེ་ཁོ་ན་ཉིད་འདུས་པའི་སྙིང་པོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    3E87:
      image_group_id: I1KG12312
      title: ''
      total_pages: 342
      order: 1
      base_file: 3E87.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
