id: P000764
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG12299
  title: བོ་དོང་ཕྱོགས་ལས་རྣམ་རྒྱལ་གྱིས་མཛད་པའི་དཔལ་དེ་ཁོ་ན་ཉིད་འདུས་པའི་སྙིང་པོ།
  author: ''
  volumes:
    b99e47356a754b4d8775a579e3d0c25f:
      image_group_id: I1KG12312
      title: ''
      volume_number: 1
      total_pages: 342
      base_file: v001.txt
